steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '--tag=$_IMAGE:latest'
      - '--build-arg=VITE_SUPABASE_URL=$_SUPABASE_URL'
      - '--build-arg=VITE_SUPABASE_ANON_KEY=$_SUPABASE_ANON_KEY'
      - '-f=Dockerfile'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args: [push, '$_IMAGE:latest']
images: ['$_IMAGE:latest']
options:
  logging: CLOUD_LOGGING_ONLY
